const users = [{
        id: 1,
        profile_picture: Sirine,
        name: "friend",
        phone_number: "+2348123456789",
        whatsapp_name: "Beyonce",
        unread: 3,
    },
    {
        id: 2,
        profile_picture: Marwa,
        name: "friend",
        phone_number: "+2348123456789",
        whatsapp_name: "Beyonce",
        unread: 3,
    },
    {
        id: 3,
        profile_picture: Islem,
        name: "friend",
        phone_number: "+2348123456789",
        whatsapp_name: "Beyonce",
        unread: 3,
    },
    {
        id: 4,
        profile_picture: Jihen,
        name: "friend",
        phone_number: "+2348123456789",
        whatsapp_name: "Beyonce",
        unread: 3,
    },
    {
        id: 5,
        profile_picture: Sirine,
        name: "friend",
        phone_number: "+2348123456789",
        whatsapp_name: "Beyonce",
        unread: 3,
    },
    {
        id: 6,
        profile_picture: Sirine,
        name: "friend",
        phone_number: "+2348123456789",
        whatsapp_name: "Beyonce",
        unread: 3,
    },
    {
        id: 1,
        profile_picture: Sirine,
        name: "friend",
        phone_number: "+2348123456789",
        whatsapp_name: "Beyonce",
        unread: 3,
    },
    {
        id: 1,
        profile_picture: Sirine,
        name: "friend",
        phone_number: "+2348123456789",
        whatsapp_name: "Beyonce",
        unread: 3,
    },
];

export default users;